Run etcd_ctl as vcap and move directory creation to pre-start
[#119387367]

diff --git a/jobs/etcd/templates/etcd_ctl.erb b/jobs/etcd/templates/etcd_ctl.erb
--- a/jobs/etcd/templates/etcd_ctl.erb
+++ b/jobs/etcd/templates/etcd_ctl.erb
@@ -1,5 +1,6 @@
 #!/bin/bash -exu
 
+SCRIPT_NAME=$(basename $0)
 RUN_DIR=/var/vcap/sys/run/etcd
 PIDFILE=${RUN_DIR}/etcd.pid
 
@@ -7,8 +8,8 @@ source /var/vcap/packages/etcd-common/utils.sh
 
 source /var/vcap/jobs/etcd/bin/etcd_bosh_utils.sh
 
-exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).log)
-exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).err.log)
+exec > >(tee -a >(logger -p user.info -t vcap.${SCRIPT_NAME}.stdout) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >> ${LOG_DIR}/${SCRIPT_NAME}.log)
+exec 2> >(tee -a >(logger -p user.error -t vcap.${SCRIPT_NAME}.stderr) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >> ${LOG_DIR}/${SCRIPT_NAME}.err.log)
 
 function wait_for_this_node_to_synchronize() {
   for i in $(seq 55); do
@@ -25,107 +26,111 @@ function handle_orphaned_etcd() {
   kill "${etcd_pid}"
 }
 
-case $1 in
+function create_run_directory() {
+  mkdir -p ${RUN_DIR}
+  chown -R vcap:vcap ${RUN_DIR}
+}
 
-  start)
+function main() {
+  create_run_directory
 
-    trap handle_orphaned_etcd TERM
+  case $1 in
 
-    <% if p("etcd.require_ssl") %>
-      set +e
-      /var/vcap/packages/etcd-dns-checker/bin/check-a-record <%= p("etcd.dns_health_check_host") %>
-      if [ "0" != "$?" ]; then
-        echo "DNS is not up"
+    start)
+
+      trap handle_orphaned_etcd TERM
+
+      <% if p("etcd.require_ssl") %>
+        set +e
+        /var/vcap/packages/etcd-dns-checker/bin/check-a-record <%= p("etcd.dns_health_check_host") %>
+        if [ "0" != "$?" ]; then
+          echo "DNS is not up"
+          exit 1
+        fi
+        set -e
+      <% end %>
+
+      pid_guard ${PIDFILE} "etcd"
+
+      if ! mountpoint -q ${STORE_DIR}; then
+        echo "WARNING: $STORE_DIR is not on a persistent disk as recommended"
+      fi
+
+      export GOMAXPROCS=$(nproc)
+
+      create_cert_files
+
+      # Allowed number of open file descriptors
+      ulimit -n 100000
+
+      prior_member_list=$(member_list)
+
+      if [ -z "${prior_member_list}" ]; then
+        cluster_state=new
+        cluster="${this_node}"
+      else
+        cluster_state=existing
+        cluster=$(extract_cluster_from_member_list "${prior_member_list}")
+
+        # If this node is not in the existing cluster, add it. It generally should
+        # not be in the cluster, but if a prior shutdown failed to remove it, we
+        # don't want to have it duplicated in the list (etcd server will fail to
+        # start). Note extract_my_id determines membership solely based on IP, so
+        # this logic is not future-proof against changing node names or ports.
+        my_id=$(extract_my_id "${prior_member_list}")
+        if [ -z "${my_id}" ]; then
+          member_add
+          cluster="${cluster},${this_node}"
+        fi
+      fi
+
+      # Sleep to allow member_add to propagate to entire cluster because starting
+      # the server subsequently expects all peers to agree on the cluster members
+      sleep 2
+
+      /var/vcap/packages/etcd/etcd ${etcd_sec_flags}                                              \
+          --name                        ${node_name}                                              \
+          --data-dir                    ${DATA_DIR}                                               \
+          --heartbeat-interval          <%= p("etcd.heartbeat_interval_in_milliseconds") %>       \
+          --election-timeout            <%= p("etcd.election_timeout_in_milliseconds") %>         \
+          --listen-peer-urls            ${listen_peer_url}                                        \
+          --listen-client-urls          ${listen_client_url}                                      \
+          --initial-advertise-peer-urls ${advertise_peer_url}                                     \
+          --advertise-client-urls       ${advertise_client_url}                                   \
+          --initial-cluster             ${cluster}                                                \
+          --initial-cluster-state       ${cluster_state}                                          \
+          2> >(tee -a ${LOG_DIR}/etcd.stderr.log | logger -p user.error -t vcap.etcd)             \
+          1> >(tee -a ${LOG_DIR}/etcd.stdout.log | logger -p user.info  -t vcap.etcd) &
+
+      etcd_pid=$!
+
+      synced=false
+      wait_for_this_node_to_synchronize # mutates $synced
+
+      if ${synced}; then
+        echo ${etcd_pid} > ${PIDFILE}
+        chown vcap:vcap ${PIDFILE}
+      else
+        safe_teardown "${prior_member_list}"
+        kill -9 ${etcd_pid}
         exit 1
       fi
-      set -e
-    <% end %>
 
-    pid_guard ${PIDFILE} "etcd"
+      ;;
 
-    if ! mountpoint -q ${STORE_DIR}; then
-      echo "WARNING: $STORE_DIR is not on a persistent disk as recommended"
-    fi
+    stop)
 
-    export GOMAXPROCS=$(nproc)
+      kill_and_wait ${PIDFILE}
 
-    mkdir -p ${RUN_DIR}
-    mkdir -p ${LOG_DIR}
-    mkdir -p ${DATA_DIR}
+      ;;
 
-    chown -R vcap:vcap ${RUN_DIR}
-    chown -R vcap:vcap ${LOG_DIR}
-    chown -R vcap:vcap ${DATA_DIR}
+    *)
 
-    create_cert_files
+      echo "Usage: etcd_ctl {start|stop}"
 
-    # Allowed number of open file descriptors
-    ulimit -n 100000
+      ;;
 
-    prior_member_list=$(member_list)
+  esac
+}
 
-    if [ -z "${prior_member_list}" ]; then
-      cluster_state=new
-      cluster="${this_node}"
-    else
-      cluster_state=existing
-      cluster=$(extract_cluster_from_member_list "${prior_member_list}")
-
-      # If this node is not in the existing cluster, add it. It generally should
-      # not be in the cluster, but if a prior shutdown failed to remove it, we
-      # don't want to have it duplicated in the list (etcd server will fail to
-      # start). Note extract_my_id determines membership solely based on IP, so
-      # this logic is not future-proof against changing node names or ports.
-      my_id=$(extract_my_id "${prior_member_list}")
-      if [ -z "${my_id}" ]; then
-        member_add
-        cluster="${cluster},${this_node}"
-      fi
-    fi
-
-    # Sleep to allow member_add to propagate to entire cluster because starting
-    # the server subsequently expects all peers to agree on the cluster members
-    sleep 2
-
-    chpst -u vcap:vcap /var/vcap/packages/etcd/etcd ${etcd_sec_flags}                           \
-        --name                        ${node_name}                                              \
-        --data-dir                    ${DATA_DIR}                                               \
-        --heartbeat-interval          <%= p("etcd.heartbeat_interval_in_milliseconds") %> \
-        --election-timeout            <%= p("etcd.election_timeout_in_milliseconds") %>   \
-        --listen-peer-urls            ${listen_peer_url}                                        \
-        --listen-client-urls          ${listen_client_url}                                      \
-        --initial-advertise-peer-urls ${advertise_peer_url}                                     \
-        --advertise-client-urls       ${advertise_client_url}                                   \
-        --initial-cluster             ${cluster}                                                \
-        --initial-cluster-state       ${cluster_state}                                          \
-        2> >(tee -a ${LOG_DIR}/etcd.stderr.log | logger -p user.error -t vcap.etcd)             \
-        1> >(tee -a ${LOG_DIR}/etcd.stdout.log | logger -p user.info  -t vcap.etcd) &
-
-    etcd_pid=$!
-
-    synced=false
-    wait_for_this_node_to_synchronize # mutates $synced
-
-    if ${synced}; then
-      echo ${etcd_pid} > ${PIDFILE}
-    else
-      safe_teardown "${prior_member_list}"
-      kill -9 ${etcd_pid}
-      exit 1
-    fi
-
-    ;;
-
-  stop)
-
-    kill_and_wait ${PIDFILE}
-
-    ;;
-
-  *)
-
-    echo "Usage: etcd_ctl {start|stop}"
-
-    ;;
-
-esac
+main "${@}"
